---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: woodpecker
  namespace: ci-cd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: woodpecker.sk8server.me
spec:
  hostnames:
    - woodpecker.sk8server.me
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: woodpecker-server
          namespace: ci-cd
          port: 8000

