---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: woodpecker
  namespace: ci-cd
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://ghcr.io/woodpecker-ci/helm/woodpecker
  ref:
    semver: ">=1.0.0"

