apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-secrets
  namespace: ci-cd
stringData:
  #ENC[AES256_GCM,data:IP3YhMieMULAOmh1e5iQY1irj9k+3GptW1n0,iv:n7+ZzOUkM/S/xUEzYdmluqV22tgtTdmC5VuSSgDYfc4=,tag:cOtZRZOBinVS5d8/rDvfBA==,type:comment]
  #ENC[AES256_GCM,data:StP4Sof5VWVrh20dSxIraeYzuIY4+lIVW1zJc3hRlOMUaHd2c3mrAxkbePJ26k4wVTA=,iv:1PhyGgZA02pTXsFkPffzgsNajMTnMBFG+ERIBMoV2ns=,tag:0IpRfnP1Ku2eB8P+xBR0ag==,type:comment]
  WOODPECKER_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:FzkwYm7hKZlkmHgBJWrBNInEcCk=,iv:4pA5eEd48vLb3qLGgfA7Oya9krG/+jos45kQwvrYOCo=,tag:7030v/wZz7aedkpuqFVOWA==,type:str]
  #ENC[AES256_GCM,data:9Z53rTJ7DyVDx+tL8WNBDnHFmDVnrGbV/Thsy1n9pw==,iv:zDtf6Hb71VPTLDMxSdSLBhQKR+3LGG4ML66gk5bIJvc=,tag:ex4xXuG0GBlpBcT9gNwT+w==,type:comment]
  WOODPECKER_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:xOU/SmGr4HdfjmOGMYBoPjtz7r+VmuxrBEJxLEwCpyNNlwDOPIOQwQ==,iv:JFA82N6phyL6nOYjOL5tu++VEBSzETfRtswP+F4rQY8=,tag:Jc8h7oimmgL/HQSHlCZLwg==,type:str]
  #ENC[AES256_GCM,data:Up7zDCrAKvpHQpF3R5/jKhTW0JQRElGxXEbPZ85+gqoQ+DHN29j0jum3yVM8,iv:jblJ7K89zZWeNf0+9MNnogcUb26BQXZ++o/XE7mFyyE=,tag:6J1CzawNJXQDATJAJP0H3A==,type:comment]
  #ENC[AES256_GCM,data:BzZd1iNTt7ACb0DR4nu2LvEB9OLL+SBBvmN6Y5jSHsmKvFBz,iv:Tip47xPzRrSUdjA4LMqzs8ml6WmMJEEojXrCPGpn/I4=,tag:FFu8oguz2SDm9xb+P0EgQA==,type:comment]
  WOODPECKER_AGENT_SECRET: ENC[AES256_GCM,data:xjIHtdEbluFrqZhh0hurm1UnQE4NlYztQ9jCnK+1pKL+/OKTVg3Eikx5ZyNIrioHfMn4kTnuC3q2PPHNu14AOQ==,iv:3YIBI4wZd6t205uT+oRqCoCJf/1G2FrMctm+QGjLSXQ=,tag:ZhPV7SIdbulNQUzvimzIHw==,type:str]
sops:
  age:
    - recipient: age1a8ffe7qngnu4h6cl2dzwmpjfvla8c0t5q6vmya5ej86htc0ey5qql2f6we
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZWtYVlgvajdxM05vSEZH
        ZEFFT2htTE1vbzYwUjdjV09uTGE1UFVRdVVNCmhUSnhPVHRuMTlCVk5SN3pYd1M4
        akpXTXdKcDd4RW81QWZoTkpEblJNcnMKLS0tIDI0bllSaENUOWsrbjFwWW1lTytO
        eUFiTkhiOUY1QzBOcy9rQnNBdjBEemcKpPf4zOlzJHppo069+x5oATX418iy7lMs
        pOXcJOb+9CUOXpUQHHO3xzjvkWXChNe1wv5Ng2Ao6hKoNw7ERHe7eA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T14:32:53Z"
  mac: ENC[AES256_GCM,data:6FfjmjVCE1Mpsw2ZF8ohM5Hh8z+BBYLLuvIBvDi6xLX3UObYW9uz7beuB20Ni0mKzloCAsWOk7VqWDG8tuM8E7dQ+7asT6QlC53qSotswN0vU/rDTsmzegR5EAL468tA+ylq+qjqJGg0mCaJ9tlB1Nhb2XXlBKCMsGbwEoCKqiY=,iv:ilysDRjUgJOXdB3tNNoas8GW5FO1u4AXbfvSvXlajGo=,tag:+IjOljlcArw+Eu00uGxHWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
