apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-secrets
  namespace: ci-cd
stringData:
  #ENC[AES256_GCM,data:4kzdZUmtB49Nbxm1v7RF363Hx/1exEV+T9Mh,iv:3m1HHTjRGGswEUyhALTzHGHht1ZE+DQsVbEnbqxAo7Y=,tag:4yEYRB9Krz7jz4dUs6B2zA==,type:comment]
  #ENC[AES256_GCM,data:HiB8n0JynY0JGy9nO/2KrD+v1083XU+YHOA3atxfsEEv0ouE8oJ/ZULBXNo4KcNgnC8=,iv:GVvlza7lfsv4K8I+E0tmCJjm4TpkM73U8A3yVLGDiuM=,tag:duOsDGmEmN7W0HTHsOrEBw==,type:comment]
  #ENC[AES256_GCM,data:LJZeZGmDrlVzoYB7uYyMA94Lqzy/J6xFy6Er,iv:hyKBQ54TP0n36KEB08q6wbWGYBuuC+jnkKP9cD8eNFw=,tag:GRlyEZ0lEl+eH4oEOtvd8g==,type:comment]
  #ENC[AES256_GCM,data:xYJKagLCFnJ7OZQ67P1y9FbOdQhXR8jr1UM6JAAO4mxwECjvt3w/bLU3OKtwUbr+tIC/ul5A0jSGOWgkxlX+,iv:+CxaPM18gZWfKhbzF0HinF/cs1Q+rL5WenP6KyMNKuA=,tag:8C7TvxAg/QsBs6k+R+fWcg==,type:comment]
  WOODPECKER_GITHUB_CLIENT: ENC[AES256_GCM,data:/tAAsfiQfF0bpLNVO7rp88qGqbw=,iv:HoIA/8EhNfrsCj2/tUbQETqir5xItF9chCf0dq8eRBI=,tag:psKIIwj4YxYoFvsHx4PGKA==,type:str]
  #ENC[AES256_GCM,data:cryzKHdhVvBL5xi8EinkpiPrBs72wiqctdR/Bo0h0A==,iv:FFT3aCmiun1yqfnULufZk8IPTYwLKbQt6eGX7i64Xg0=,tag:plYUK3b/faB5e4EK77l+og==,type:comment]
  #ENC[AES256_GCM,data:zDufG2kYA2klfoONe+UkoHy9uRkgZzf10UlprRjskOFCnu9b8RIG3mJPfIqeKqnFU6o/7SPmfjk9Cn2u+XibSMnxpg==,iv:n0JL5JleK/766kr6DjXRdfb6ucKiNe/zvDM2eZn+AIQ=,tag:icj5Vp7ozsHacQWXlb+LOg==,type:comment]
  WOODPECKER_GITHUB_SECRET: ENC[AES256_GCM,data:oU3qIefpFp8aW2ey2Pr4jssfJVN8fZ7vsJkhs0RcXsJnvV81Jnf5Kw==,iv:uCsJS5wGKRz/glwT9aeG0v2iQcs4v/ToHFXv93T8qZc=,tag:J0Oj5YsuPHpwnxaB/9T5VQ==,type:str]
  #ENC[AES256_GCM,data:auU/7ZwbEVucVsFrRE0noit7yzxjI01C1gMAYfvf/afrJ8O22rhvDTy1H9He,iv:vbqPshGUbvFPkJDJQZqHmYaYRXhERm3M00Wf++HN5Qw=,tag:yugCnqzzfTYjDgj4kAOpjA==,type:comment]
  #ENC[AES256_GCM,data:Zz/x4P3J36Un/F9xmBCHP9YwsKmY4knogzA6MMlLDmcIXfsR,iv:If4hciIbJscqdr4MHAZZVg/KtYJYlupxbVFuv3QpwmU=,tag:p6R+J/CZ2ZFM3zeicMrRtg==,type:comment]
  WOODPECKER_AGENT_SECRET: ENC[AES256_GCM,data:DHJ58Vl/ewR2cM0RYMSlLLUHAk7u5+Gr0iulmHmB6BK4tzTqZ8b0pcOvctQm4Os3o1wbB7l5+nN+cMxfS2b5mQ==,iv:dgQlytI5SYwtXzLJhydQckbZ+zrogVO1BhWIrjAAWKo=,tag:ZrXgbBg4M+CalPPt9Q0lRw==,type:str]
sops:
  age:
    - recipient: age1a8ffe7qngnu4h6cl2dzwmpjfvla8c0t5q6vmya5ej86htc0ey5qql2f6we
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWlF4MnVRUjQxdnBZd3Zl
        b1hnR04xU1FwK3NLQUJER0xpdk0wd2NYMFUwCjI1eUNJWU9ncUIxSS9HNnFjT3Zs
        bENRQWowUm90VmdyaFR6V0ZQbmxLL2cKLS0tIHF0V09BcGVvaTNocHMxQUNxeVhk
        Zlp1clJ1RENzQmVxeUE3Y2VscTFJRHcKw7wmjYQ1/1oIG/z138HK5F0K/w87BAOu
        3fQvntqsV3RkDf2RVMLvDShiSWW0HFGZmKV4zZsHQt4Kmc3Q0iYFDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T15:31:43Z"
  mac: ENC[AES256_GCM,data:Mmo1BcgN4lg5FQhvVWtF1J/Z+plFAAthzxG3eUOZ0OZjmhxSzFFdiv4TMZdP7x9Nk7TF3hWeUUBjHxZkZuAZG5FLKTDBrJxV+S/SB9ohhp8wcev7pDVjWQTHx60y8Vif+0Grxk8Qd7mn91ODHTfZ83Q8Nac5mJ3ZmEStQUX3JBM=,iv:4HdD6H83UnC6W+kTmwkHJvO3oSrCYIN7Ppcm5kekrmQ=,tag:JO6R97fvihQKLDBqWYEWog==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
