apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:D1u4CZNAjqeDA1TFN6FUaBMNtxOKfmVNztV282Dw1MumJFcKtrP6iQ==,iv:3fPIg3UxTMwDshHVV8C3YD3Rl79SPV71NxEx4v7xJOQ=,tag:aLbucJdcpZ4ONFUISSzszA==,type:str]
sops:
  age:
    - recipient: age1a8ffe7qngnu4h6cl2dzwmpjfvla8c0t5q6vmya5ej86htc0ey5qql2f6we
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0M2dKWExjVTVIM1VFS1lH
        bXNqcmF2YmlCQkhTUXVFUFFxYkZXYUIrVWswCmhRQmMydmFhUzVWc0VLOVAzZXBB
        eFoxOXYyT2lLcjI1NTJOTnhJU2tuOGsKLS0tIERYb2t6RTJuQlk2THdzQk9lajQz
        SnBHSTRpNE02V3ZzQ21NNmN1YkIrbzQKumPCSyLhKYiyoXW/PDvzKYB6hIPQPvsp
        qwknBf7nBkm5NwU5cXH7+adZtareXy7+K/nEybuuXsR5Af6YDcH53Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-10T17:40:56Z"
  mac: ENC[AES256_GCM,data:5poC6ZXXP33/60bmSNRD9dTcbuDARdu8ZgewvP7FBHxsX2mrGf2mM8h1yk+UYO1gULWLOkucgQRw6M+mqE4sqM1ekPiOXikI0uU/qPOY9pfp/+ETig77xhoqwywRJjOwWY0bnBDJxQaAiJxk5mF7Bh5sUS+fc4dKPQNSuWWmHg8=,iv:1hWnfyvoFva+e+kia9XxvtqwFGf0Bni/O7EgdfgaWy8=,tag:3s9jI0JZRyYmWSKpzW0P3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
