apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:8UpPelRWRXDcfv10,iv:nldnoM9zty364flaR1kJ2NmP3MwUVk90utS04T87xXE=,tag:6+4gqbNovr58z5iXJOSYYQ==,type:str]
sops:
  age:
    - recipient: age1a8ffe7qngnu4h6cl2dzwmpjfvla8c0t5q6vmya5ej86htc0ey5qql2f6we
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Yzh4TkNVcFQwemV6VEFX
        WElZQlM2NGt2d296cW8vNVZFMjV3SzJYYnpzCjE5dkhkaWtsWUFmV3ZSVGVTaWpO
        R3dJTWNPMEduelBhSUlJR0ZwUmJZYTQKLS0tIEdWdFI2Q0JMNUZQNzJ4ancvREcv
        NkptZHpiUkNHWWxQU3lNNXEyYjM4Q2cKZF+olFQy/oVKv3YfZ36QbaIdtl0Iahgp
        9E6QRmnLvLu5vhLvj1s5GZ5SM+cXcbQYNt5zf1fG09VQCuYLIi/SAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-10T17:40:56Z"
  mac: ENC[AES256_GCM,data:Hd2NhrxXiSwHAYrcLoaQET4DQV+1/uwNpN8ld/EaXOqTU+15qKAetzWYK1MsdXKPyPMRsY2mj7RUQEszlSgZzkZxg3RYk3ZqXXkSwtSjtcl8cJuYdaNupc8v7KKJ/hgGY87/otb+qOlbXHTGDv9GTwUZ92ToCXBBLgyiVYlkUNE=,iv:pLXq0/soPezwk8U5Ke+x5P5Rr8+z6B3DarKOg1dl3tk=,tag:bI/8Q6HfiTwpY2QSss10UQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
