apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ppyLwLZrd5RVdbed/X0KhpgDpyvrh9j7X52VM20cmr8=,iv:+ZCReE9jKKNstHOiFIHirJPAPF7WySIeQeub+6kZ41o=,tag:kyYUVA5ZjqavV8OtpGilhw==,type:str]
sops:
  age:
    - recipient: age1a8ffe7qngnu4h6cl2dzwmpjfvla8c0t5q6vmya5ej86htc0ey5qql2f6we
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZT0J2ZkNZT3NDVzNNVXB4
        Q2RLYm9EZ0pzbmxCOGdpTXhQcmxSbGZTMG5BCjhDNTF5dmRpUXNyUTRtQkNRN05V
        bVIzRUJBTTRET2ViQ0EzLzJIWk1PMTAKLS0tIFlTWHdkQmo3ZmVCTUlZWEtwSjJC
        TTVURFIvOGhEdmxKVmYwWE9vNEJaNm8K0ZJ+qftgOeJQdNMqokyUOJD0LutDVuKg
        iKXitdlbQTVPiGb+OY2RAMEYQX0f1Fnp+DPKH1cilbCoTPEFtJ3zyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-10T17:40:56Z"
  mac: ENC[AES256_GCM,data:RcMPM4pfwCvBi/iWngczvowp4LLbXMLj87FgvKSpGMyuZ0YTi+SXSFi6ppgu2TlW6Bickih0FYgxYg5B+nuEdONFjbLvjwQwz0jelOg0Qukt1Tmey3Y/71tpSShmr1vSbT8F9L+9EDjlY5+PH1MdNMRFGzNwg4epN/lQA6OvCUw=,iv:RBFI9dJzYx3+xQUTksIxMnH1Ql/8Dr+bycg9Tw8DGxk=,tag:kUcqKL/m5NNtY2ogs+o4og==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
