apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  admin-user: ENC[AES256_GCM,data:FRtxVUc=,iv:7iT8gcp3fdYduHPo+FM2eoZi0uAtsIuCFgrPC+OkH8o=,tag:ycx9MkdJ7KeS1NLd2LJz9A==,type:str]
  admin-password: ENC[AES256_GCM,data:8Goj068BKi5T,iv:xVueIGQbzua+KRFkpzJy00kypR9v/4RMI3KHF/1h6OI=,tag:m5wt1tUiQyvn8BqgJrLmHw==,type:str]
sops:
  age:
    - recipient: age1a8ffe7qngnu4h6cl2dzwmpjfvla8c0t5q6vmya5ej86htc0ey5qql2f6we
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMHJYMlREM1RWcHpvdjRS
        cWh6UEVIRFYrN1ZzRGllK2hkOVBIc2sreTFBCmtBTU9LeFN1KzRVdENQMzA2empH
        KytVTEw1WmRobi9Ndm12dld4bm1FdVkKLS0tIHhRSmRQSFNWNzJLcmRyWXpTajBx
        ZSs4ZUxNUFZnRGdRcWpHL0doeEJrLzAKJ6KANN4Hsb83JDxeij18Waz1nHvmEKy0
        BDjrzyET2X4JFrQyhlZORu9kxbFGgYwpA/Z7Hkng2yXMI4QQU10xOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-10T19:11:59Z"
  mac: ENC[AES256_GCM,data:7gbFBLsYoCLItw+vu27JcwDUFYKspDNw2BgtUHGFeCaPhhhQP/ksZJfAar7wO/goyBM7mi7JbQ6K1kE8kZUNzplckZK1k8svx5mveUiiDVfNd2krcxXVn9KFd8zFyWg+tlaGFOIk6vgluMbjkrxCyldSny19s6vqil6PNKdFa74=,iv:rEtTCCGTrLlQkKlTOPEmBHMQh6QLkhnbLwHyZGWNdSA=,tag:nSq29BADcs9LDGbm9EQOlQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
