apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:WY3wAIgKNOrTeRJU4fZfV6Rwx3HZBjJpDzNUx4aXXkmiZKWcGk6XKr4i7S0+ZtESExnekXepLpROeTTWgqvnjWzNNOkGmFUKxVycxXqdxjKiyjopc6hb4AmCwkSEBnvmL3edMyxF2AMJwsaDykWf1htK1zlZmKb25MePD9dp2em57XqPG2vvnCnC0qkviCGcqpyKpZAUrxZPqrkvx/4XYFUeTGt6C4Ybb+bqtTMhNxc0RE6J,iv:xUO86z1DAHFAQ/RBBzB42op5EZjFUA/YSU26ZXK95E8=,tag:nJBciZuwV84iOAC1PzDKGg==,type:str]
sops:
  age:
    - recipient: age1a8ffe7qngnu4h6cl2dzwmpjfvla8c0t5q6vmya5ej86htc0ey5qql2f6we
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNjdDeDMrWXc1VW5zd3Yx
        RFM0Z0Rxa0tBM3poSjg5dStjbWJWaHMvc2xVCnR4UndLMjhhejhHdThkU3N3K0lP
        eDk4citTZytJenhlQlFXdEVvWVRlUjgKLS0tIC80alFkUGIwUHM4S20xWXRqWFRy
        VkdvZC82SHBkbC9ZRnIwOTF6SnRVdTgKTAFNPttW3/9i6q8FQGgG5HVMmzMisebr
        in+vDyloJm7F1Nf/5GPuUXkVWOi9pXcfgibR72Ib4P8LuzSjuNW1RA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-10T17:40:56Z"
  mac: ENC[AES256_GCM,data:DD78+tWNJrsMTdalcvJ/yAILWqm7ZGYbYtu+eWw7i9C0ZSxVQ+Fvj0b+q00n0NShgXJSn7jos7j02THCnBowA0evsHolgbPZL/1GGpLr2QN4I1/FXji3kVMMwPo2jjYnzDAFYmA6qeptgRidudv7K3dCv8kaNWtlD57qr2nXKA0=,iv:xSwVcizszZe9xknI8SsZM/I0+3maINbMal4o3B6pA8s=,tag:6wAlIAWVM1USGLBWLqI+Iw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
