endpoints:
  - name: Kubernetes API
    url: https://kubernetes.default.svc:443/healthz
    client:
      tls:
        ca-certificate-file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    conditions:
      - "[STATUS] == 200"
  - name: Grafana
    url: https://grafana.sk8server.me/api/health
    conditions:
      - "[STATUS] == 200"
  - name: Prometheus
    url: https://prometheus.sk8server.me/-/healthy
    conditions:
      - "[STATUS] == 200"

