apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:BlLK4i6BEVsL9zz2Aivajz/2RjyWkXov0gjZHvnb49GcJooDeH+V7A==,iv:a1nuf8dZHMsIKHNLXnAJWkmoEv5zTKHelaR/luHmfA4=,tag:ynsVYDJ4+CwHuZqiBcrO8Q==,type:str]
sops:
  age:
    - recipient: age1a8ffe7qngnu4h6cl2dzwmpjfvla8c0t5q6vmya5ej86htc0ey5qql2f6we
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZHduSFJlRVhvWHVjS2Ir
        VENDcnV1eTVzci9paWYwQ0VNNUZVQkJXM3dnCnIzbEtrc0kva0g0V013K0Nmc0ZU
        MHRNenNDL1FyQnIvQU9LblJibXZEZWMKLS0tIDRlamduRnNoMU8xZXpHYzVDRnBU
        UkNVdXZuSkw3SG5UcE03Tk1aQW9rWlEKQquAXBdr/aZAvTZlYbcGb9zrZaKOgRrf
        XthbdHvzdHemDN4EFC9kMcnF9K3EeQocpUFSI+0Khh7HM7y4elO9Zg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-10T17:40:56Z"
  mac: ENC[AES256_GCM,data:en0PzL0sVN9nuLSdYFCZgnY87xJGTUt/1rW+Mg+v7ZDwy83T9q7dPke8N31iKqzACdeyoFBshfeyr0QAw49Ky5dY28mARTc8ZyDj5ITJbQOaJz2VF1gUKUTdeWJIx6VA7zCgAat75H9PuS5qvn+3+xQaQuzdlc6Uovc4FbOXduQ=,iv:dmPcF508S3QytFgPHqFxGjSrBz21MkOMc4ggIsTf3tA=,tag:g/VLup78JcWQvisVZGdL5g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
